Added new values for subcategory (traffic)
smart-data-models/dataModel.Alert pull request #5
Opened 2021-05-07 09:33 UTC by aqueralt

Added the values "pedestrianOnRoad", "bikerOnRoad", and "tramApproaching" in Alert subCategory, for alerts related to traffic events.

2021-05-12 09:35 UTC, albertoabellagarcia commented
Could you provide the use case in the ADOPTER.yaml file? 
https://github.com/smart-data-models/dataModel.Alert/blob/master/Alert/ADOPTERS.yaml
Thanks

2021-05-12 09:37 UTC, albertoabellagarcia commented
Thank you very much but specs are generated automatically so, you do not need to PR these documents, once accepted they are updated. 
You only need to PR on the schema.json (and in the ADOPTERS.yaml)
Thanks

2021-05-13 10:47 UTC, albertoabellagarcia requested changes
I'm going to accept the changes but not through this PR. 
sorry for the job you did on documents that are automatically generated. We've modified our process to include a note about not doing it in the header of specifications. 
Like this [https://github.com/smart-data-models/dataModel.RoboticIndustrialActivities/blob/master/Pallet/doc/spec.md](https://github.com/smart-data-models/dataModel.RoboticIndustrialActivities/blob/master/Pallet/doc/spec.md)

2021-05-13 10:47 UTC, albertoabellagarcia commented on Alert/doc/spec.md
PR on this file is rejected

2021-05-13 10:47 UTC, albertoabellagarcia commented on Alert/doc/spec_DE.md
PR on this file is rejected

2021-05-13 10:47 UTC, albertoabellagarcia commented on Alert/doc/spec_ES.md
PR on this file is rejected

2021-05-13 10:47 UTC, albertoabellagarcia commented on Alert/doc/spec_FR.md
PR on this file is rejected

2021-05-13 10:47 UTC, albertoabellagarcia commented on Alert/model.yaml
>              - roadWorks
PR on this file is rejected

2021-05-13 10:47 UTC, albertoabellagarcia commented on Alert/schema.json
>        "properties": {
ok

2021-05-13 10:48 UTC, closed without merging

2021-05-13 10:49 UTC, albertoabellagarcia commented
As explained before changes are accepted but PR no.
thanks

2021-05-13 10:55 UTC, albertoabellagarcia commented
Updated

2021-05-13 13:05 UTC, aqueralt commented
Many thanks, and sorry for the inconveniences. I will update the Adopters file asap.